// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq9wIuWr7UzaTpM3y2Lv24olsztlcc6CI',
    appId: '1:182201856143:web:514408170f02cda54840fa',
    messagingSenderId: '182201856143',
    projectId: 'chat-app-a0694',
    authDomain: 'chat-app-a0694.firebaseapp.com',
    storageBucket: 'chat-app-a0694.appspot.com',
    measurementId: 'G-JK5V2DK2ZH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBAblIga5Q1Eai7LqBldcnqHDz_Bglaac',
    appId: '1:182201856143:android:47f9f76837ee71be4840fa',
    messagingSenderId: '182201856143',
    projectId: 'chat-app-a0694',
    storageBucket: 'chat-app-a0694.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTauVmnu8FZpUTBglVwGMsBbaxTo8u444',
    appId: '1:182201856143:ios:0cf1a8cd1e7bc35a4840fa',
    messagingSenderId: '182201856143',
    projectId: 'chat-app-a0694',
    storageBucket: 'chat-app-a0694.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTauVmnu8FZpUTBglVwGMsBbaxTo8u444',
    appId: '1:182201856143:ios:0cf1a8cd1e7bc35a4840fa',
    messagingSenderId: '182201856143',
    projectId: 'chat-app-a0694',
    storageBucket: 'chat-app-a0694.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAq9wIuWr7UzaTpM3y2Lv24olsztlcc6CI',
    appId: '1:182201856143:web:be87d53d70b7e9d34840fa',
    messagingSenderId: '182201856143',
    projectId: 'chat-app-a0694',
    authDomain: 'chat-app-a0694.firebaseapp.com',
    storageBucket: 'chat-app-a0694.appspot.com',
    measurementId: 'G-C28VBE8JHJ',
  );
}
